# Generated by Django 5.2.16 on 2026-07-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_topic_studysession_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#c23b22', max_length=7),
        ),
    ]
