services:
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: study-time-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
